### ISSUE TITLE
Write scrabble words without the board?

### ISSUE THREAD

**Issue by jmbeckers** [cpierquet/Scrabble#1]
I guess there are some functions that allow to write scrabble words (with tiles) but not placing them on the board ? Typically when you want to provide examples and rules in a text without redrawing the whole board that would be handy. 

I tried to understand the .sty file but since I'm not an expert in developping .sty files I'm not able to find the functions I would like to use.

Anyway, very nice work.

**Comment by cpierquet** [comment]
Hi-
In the last version (0.1.4), there's a macro to insert inline words with tiles :-)
![image](https://github.com/cpierquet/Scrabble/assets/45103962/487921c2-59b6-4ca4-9c63-0de85b43ec85)

**Comment by jmbeckers** [comment]
Great; when do you plan to make 0.1.4 available ?

**Comment by cpierquet** [comment]
Already available in TeXlive :-)
![image](https://github.com/cpierquet/Scrabble/assets/45103962/16c2d469-abfd-4543-adc7-81142c146944)
