### ISSUE TITLE
Ö Ü Ä not supported ?

### ISSUE THREAD

**Issue by jmbeckers** [cpierquet/Scrabble#2]
Hi
Ö Ü and Ä are valid srabble letters in german, but I cannot make it work under latex. I tried several combinations of inputenc, babel etc, without success. "Improper alphabetic constant" is a typical error message.
Looking into the code 
\def\AlphabetMajuscule{ABCDEFGHIJKLMNOPQRSTUVWXYZ}

does not seem to define the letters.
Any chance that it could be added?

**Comment by cpierquet** [comment]
Hi-
I can see if it is possible to add these letters for the German version.
But it would be necessary to create a specific alphabet for the German language...
So I'm watching all of this ! :-)

Céd-

**Comment by jmbeckers** [comment]
If I modify scrabble.sty by using

\def\AlphabetMajuscule{ABCDEFGHIJKLMNOPQRSTUVWXYZ104}
\def\AlphabetMinuscule{abcdefghijklmnopqrstuvwxyz104}
\def\PointsScrabbleFR{1,3,3,2,1,4,2,4,1,8,10,1,1,1,1,3,8,1,1,1,1,4,10,10,10,10,0,0,0}
\readlist*{\PtsScrbFR}{\PointsScrabbleFR}
\def\PointsScrabbleEN{1,3,3,2,1,4,2,4,1,8,5,1,3,1,1,3,10,1,1,1,1,4,4,8,4,10,0,0,0}
\readlist*{\PtsScrbEN}{\PointsScrabbleEN}
\def\PointsScrabbleDE{1,3,4,1,1,2,2,2,2,1,6,4,2,3,2,4,10,1,1,1,1,6,3,8,10,3,2,2,2}
\readlist*{\PtsScrbDE}{\PointsScrabbleDE}
\def\PointsScrabbleES{1,3,3,2,1,4,2,4,1,8, ,1,3,1,1,3,5,1,1,1,1,4, ,8,4,10,0,0,0}
\readlist*{\PtsScrbES}{\PointsScrabbleES}

I can use letters "1" "0" and "4" to mimic Ä Ö and Ü (and adding 222 for the points and 000 for non german language), but using directly Ä Ö and Ü in the .sty file does not work.

**Comment by cpierquet** [comment]
Maybe with an other system (or test with character), I need to try :-)

**Comment by jmbeckers** [comment]
Seems ok for my purposes 👍 . will you update the src file here ?

**Comment by cpierquet** [comment]
I need to send the package in CTAN and the src will be here too :-)

**Comment by cpierquet** [comment]
Version 0.1.5 uploaded in CTAN (and here) ^^

**Comment by jmbeckers** [comment]
Excellent, many thanks. Just a typo to correct in the doc:
![image](https://github.com/cpierquet/Scrabble/assets/19711382/549c615e-28e2-43a9-88c5-95258ac4ce05)
Ä and Ö are inverted

**Comment by cpierquet** [comment]
Tks ^^
For next upload in CTAN, soon here ^^
