### ISSUE TITLE
Bug de gestion du joker avec \MotScrabble et \ScrabbleWord

### ISSUE THREAD

**Issue by quark67** [cpierquet/Scrabble#3]
Extrait de la documentation : 

<img width="407" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/a2b9fa0c-b772-4338-944a-d4b35576dbef">

Le caractère `*` est affiché sous la forme d'un jeton vide, suivi d'un jeton portant le caractère `*`, au lieu de simplement un jeton vide.

La raison en est la suivante.

La ligne 388 de Scrabble.sty défini la commande `\MotScrabble`, et à partir de la ligne 397, traite les cas selon que le caractère courant de l'argument de `\MotScrabble` est `*`, un entier (0 à 9) ou autre chose. 

Si le caractère est `*` (testé en ligne 398), la ligne 400 est exécutée. Parfait, cela dessine le jeton blanc.

Puis vient la ligne 403 (qui est également traitée si le caractère courant est `*`), qui teste si le caractère est ou non un entier. Si c'est un entier, les lignes 405 à 481 sont exécutés. **Sinon**, ce sont les lignes 484 à 490 qui sont exécutées, afin d'afficher le caractère en question, verbatim. Or, comme `*` n'est pas un entier, il est concerné par la partie « test faux » de `IfInteger`, et cela a pour conséquence que `*` est affiché verbatim sur un jeton.

Pour éviter le bug, tout le test `\IfInteger` des lignes 403 à 491 devrait être placé dans la ligne 402 correspondant à la partie « test faux » de `\IfStrEq` testant si le caractère courant est l'étoile.

C'est d'ailleurs la logique qui est employée pour le placement des jetons sur le plateau. En ligne 110, on teste si le caractère courant est l'étoile, auquel cas un traitement particulier est fait, et sinon, on traite les autres situations aux lignes 111 à 154.

La même correction est à faire pour la commande `\ScrabbleWord` à partir de la ligne 516.

**Comment by cpierquet** [comment]
Merci pour le retour, je n'avais en effet pas testé le jeton joker avec l'insertion en ligne...
