### ISSUE TITLE
Proposition d'amélioration de la grille allemande

### ISSUE THREAD

**Issue by quark67** [cpierquet/Scrabble#5]
Soit le code de base : 

```latex
\documentclass[11pt]{article}
\usepackage{Scrabble}
\begin{document}
\PlateauScrabble<DE>[Echelle=0.55,Cadre=false]
\end{document}
```

Ceci produit la grille:

<img width="415" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/596dcaa9-e033-4eed-9052-3f58620a07f2">

avec les 2B, 3B, 2W, 3W car les mots allemands ont l'inconvénient d'être assez longs et ont du mal à entrer dans de petites cases.

Je vais me concentrer sur la commande `\SCRBLCD` (ligne 82 et suivantes) du fichier Scrabble.sty, qui se charge d'écrire dans les cases bleu clair, correspondant à « Lettre compte double » en français : 

```latex
\newcommand\SCRBLCD[1]{%lettre x2
	\IfStrEq{#1}{FR}{LETTRE\\COMPTE\\DOUBLE}{}%
	\IfStrEq{#1}{EN}{DOUBLE\\LETTER\\SCORE}{}%
	\IfStrEq{#1}{DE}{\scalebox{2}[2]{2B}}{}%
	\IfStrEq{#1}{ES}{DOBLE\\TANTO\\DE\\LETRA}{}%
}
```

ce qui actuellement pour l'allemand affiche en deux fois plus gros « 2B ».

En effet, il n'est pas possible d'utiliser `\scalebox{0.5}{0.5}{DOPPELTER\\BUCHSTABEN\\WERT}` pour afficher le texte en deux fois plus petit, car ce contenu est envoyé dans un nœud TikZ et la présence des passages à la ligne `\\` dans la commande `\scalebox` génère des erreurs. 

Comme la solution réside quand même dans l'utilisation de `\scalebox`, je voudrais auparavant corriger un problème un peu subtil.

Si l'on regarde de très près l'affichage de cette case bleu clair, on constate ceci : 

<img width="226" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/f09726db-eab2-4d1b-8054-db575b3bb4a2">

Le texte n'est pas parfaitement centré (il est un peu trop du côté gauche). Pour mieux le visualiser, j'ai placé par-dessus deux rectangles identiques et notamment de même largeur : 

<img width="225" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/103b32c0-3340-4733-a02c-c55bf41cc7eb">

Ce problème n'a rien à voir avec l'utilisation de `\scalebox`, mais avec le fait que si la commande `\SCRBLCD` renvoie un texte sur une seule ligne, le centrage dans le nœud TikZ dans lequel ce contenu est envoyé n'est pas correct.

Ainsi, si la ligne `\IfStrEq{#1}{DE}{\scalebox{2}[2]{2B}}{}%` était remplacée par `\IfStrEq{#1}{DE}{2B2B2B}{}%`, nous aurions : 

<img width="225" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/3dc7418d-a9e6-43f8-8d32-9eea4f59e82c">

La solution à ce problème consiste à forcer la présence d'une seconde ligne en mettant quelque chose d'invisible puis de passer à la ligne. La chose invisible peut être une ligne sans largeur ni épaisseur (`\rule{0pt}{0pt}`), mais aussi quelque chose comme `\relax` tout simplement.

Ainsi, avec `\IfStrEq{#1}{DE}{\relax\\2B2B2B}{}%`, on obtient ceci : 

<img width="231" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/17a63c8b-58da-4a50-85c4-3e8c7452c9d6">

Le centrage sur l'axe horizontal est parfait, mais celui sur l'axe vertical est moins bon. En effet, le passage à la ligne ajoute de l'espace vertical.

La solution que je propose est alors de faire un passage à la ligne avec une hauteur négative de `-1ex`, comme ceci : `\IfStrEq{#1}{DE}{\relax\\[-1ex]2B2B2B}{}%`. On obtient ce qu'il faut au niveau du centrage : 

<img width="231" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/199cf363-393a-403c-84d0-be5826ea1d2d">

En laissant provisoirement de côté ce problème de centrage horizontal et vertical, revenons à la difficulté d'afficher du texte réduit avec les arguments de la commande `\scalebox`. 

Mettre directement `\IfStrEq{#1}{DE}{\scalebox{0.5}[0.5]{DOPPELTER\\BUCHSTABEN\\WERT}}{}%` produit l'erreur `Package tikz Error: Giving up on this path. Did you forget a semicolon?.`. La présence des `\\` ne passe pas.

Après un tâtonnement à base de tabular à une colonne centrée, je n'ai absolument aucun mérite car j'ai posé une question à ChatGPT et il m'a proposé l'emploi du package `varwidth` que je ne connais pas spécialement. 

Effectivement, en ajoutant `\RequirePackage{varwidth}` dans Scrabble.sty, et en mettant la ligne : 

```latex
\IfStrEq{#1}{DE}{\scalebox{0.5}[0.5]{\begin{varwidth}{1in}\centering DOPPELTER\\BUCHSTABEN\\WERT\end{varwidth}}}{}%
```

j'obtiens : 

<img width="235" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/624a5ee4-01a6-400f-8d46-a0d4dd917184">

Une note au sujet de l'argument `{1in}` de l'environnement *varwidth* : j'ignore quelle valeur il faut donner et quel est le rôle exact de cette valeur, la documentation succincte du package n'en parle pas. Peut-être, sous toutes réserves, faut-il donner à cette valeur au moins la largeur naturelle du texte contenu dans l'environnement (en faisant abstraction des passages à la ligne, c'est à dire au moins la largeur naturelle de `DOPPELTER BUCHSTABEN WERT`, en tout cas avec une valeur de `1cm`, c'est trop court et ça ne donne pas un résultat correct).

La présence de la commande `\centering` reste nécessaire.

Finalement, le `\scalbox` composant du matériel sur une seule ligne, on emploie l'astuce utilisée plus haut pour un centrage parfait (à savoir quelque chose d'invisible puis un passage à la ligne avec une longueur verticale négative (il s'avère que la valeur précédente de `-1ex` ne convient pas, tout cela reste un peu mystérieux, la valeur `-0.5ex` semble optimale ici). J'adapte également les échelles horizontales et verticales de `\scalebox` pour obtenir un résultat optimal : 

```latex
\IfStrEq{#1}{DE}{\relax\\[-0.5ex]\scalebox{0.65}[1]{\begin{varwidth}{1in}\centering DOPPELTER\\BUCHSTABEN\\WERT\end{varwidth}}}{}%
```

ce qui produit : 

<img width="226" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/bfdae26a-0897-4ce6-b130-ac494b5483b2">

En procédant de même pour les autres textes (source : https://de.wikipedia.org/wiki/Scrabble#/media/Datei:Scrabbleboard.svg) : 

```latex
% pour \SCRBMCT
\IfStrEq{#1}{DE}{\relax\\[-0.5ex]\scalebox{0.65}[1]{\begin{varwidth}{1in}\centering DREI FACHER\\WORT\\WERT\end{varwidth}}}{}%

% pour \SCRBMCD
\IfStrEq{#1}{DE}{\relax\\[-0.5ex]\scalebox{0.65}[1]{\begin{varwidth}{1in}\centering DOPPELTER\\WORT\\WERT\end{varwidth}}}{}%

% pour \SCRBLCT
\IfStrEq{#1}{DE}{\relax\\[-0.5ex]\scalebox{0.65}[1]{\begin{varwidth}{1in}\centering DREI FACHER\\BUCHSTABEN\\WERT\end{varwidth}}}{}%
```

on obtient : 

<img width="508" alt="image" src="https://github.com/cpierquet/Scrabble/assets/9338576/9f96dd88-9e85-477f-b637-71c75071f72a">

Il a peut-être bien mieux que ce que je propose comme solution, mais en attendant peut-être que cela vous conviendra.

J'ai testé avec les trois tailles de fonte par défaut (10pt, 11pt,12pt) avec la fonte par défaut, cela semble correct (le choix de l'échelle de contraction sur l'axe horizontal reste toutefois potentiellement à adapter suivant les fontes). Je reste un peu insatisfait d'avoir plus ou moins proposé une valeur au pif pour l'espace vertical négatif. Il y a peut-être moyen d'éviter ce « bricolage » directement avec TikZ.

**Comment by cpierquet** [comment]
Merci pour le retour, je vais regarder tout ça !
